# Site Configuration
titleBase: Knex Dart Docs
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/kartikey321/knex-dart
  - name: Issues
    url: https://github.com/kartikey321/knex-dart/issues
