/// Differential parity harness: knex-dart vs knex.js.
///
/// Reads the committed fixture generated by `tool/parity/run_js.mjs` (knex.js
/// output, dialect-native) and, for every (case × dialect) entry, rebuilds the
/// same query with knex-dart and asserts identical SQL (after documented
/// per-dialect placeholder/quote normalization) and equal bindings.
///
/// Refusals are data: if knex.js refused a case (capability limit), knex-dart is
/// expected to refuse too. Divergences are either fixed or recorded in
/// [parityAllowlist] with a reason.
///
/// RATCHET: allowlisted entries are NOT skipped — they run in reverse. The test
/// asserts the divergence *still exists* in its known shape. So the moment a bug
/// is fixed (or an accepted behavior drifts), the allowlisted test fails and
/// forces the entry to be re-triaged / removed. A green suite therefore means
/// "every diff is fixed OR still-diverging-as-documented", never "silently ok".
///
/// Binding equality note: numbers compare by value, so int-vs-double width is
/// NOT distinguished (JSON collapses `2.0`→`2` anyway); string-vs-number IS
/// (`"1"` ≠ `1`). No case currently depends on numeric width.
///
/// Regenerate fixtures: `node tool/parity/run_js.mjs`
library;

import 'dart:convert';
import 'dart:io';

import 'package:knex_dart/knex_dart.dart';
import 'package:test/test.dart';

import 'parity_cases.dart';

/// Triage ledger of known divergences, keyed `id::dialect`. Every entry MUST
/// carry a reason. Two classes:
///   [ACCEPTED] — intentional & valid; knex-dart is right (often *more* correct
///               than knex.js, which silently drops unsupported constructs).
///   [OPEN BUG] — a real knex-dart defect the harness caught; fix then DELETE
///               the entry (the ratchet will fail the test until you do).
const Map<String, String> parityAllowlist = {
  // ── ACCEPTED: knex-dart refuses where knex.js silently drops ───────────────
  'returning/insert::mysql':
      '[ACCEPTED] MySQL has no RETURNING. knex.js silently omits the clause '
          '(warning only); knex-dart throws rather than drop it silently.',
  'returning/insert::redshift':
      '[ACCEPTED] Redshift has no RETURNING. knex-dart throws; knex.js omits.',
  'upsert/merge::redshift':
      '[ACCEPTED] Redshift does not support ON CONFLICT. knex.js emits a plain '
          'INSERT (silently dropping the upsert!); knex-dart correctly refuses.',

  // ── OPEN BUG: real knex-dart defects to fix (then delete these) ────────────
  'returning/insert::sqlite':
      '[OPEN BUG] SQLite >=3.35 supports RETURNING and knex.js emits it, but '
          "knex-dart's capability matrix omits `returning` for sqlite, so it "
          'wrongly throws. Fix: add returning to the sqlite/turso/d1 caps.',
  'returning/insert::turso':
      '[OPEN BUG] see returning/insert::sqlite (turso is sqlite-family).',
  'returning/insert::d1':
      '[OPEN BUG] see returning/insert::sqlite (d1 is sqlite-family).',
};

/// Dialects the core harness cannot drive via [KnexQuery.forClient].
const Set<String> _skipDialects = {
  'mssql', // not a core SQL-gen dialect — lives in the knex_dart_mssql package
};

/// knex-dart uses SQL-standard double quotes for SQLite; knex.js sqlite3 uses
/// backticks. Both are valid SQLite identifier quoting — normalize the surface
/// so the rest of the statement is still compared strictly.
const Set<String> _sqliteFamily = {'sqlite', 'turso', 'd1'};

String _normalizeSql(String sql, String dialect) =>
    _sqliteFamily.contains(dialect) ? sql.replaceAll('`', '"') : sql;

/// A legitimate capability/validation refusal (as opposed to a typo in a case,
/// which would be a [NoSuchMethodError]/[TypeError] and should fail the test).
bool _isRefusal(Object e) =>
    e is StateError || e is ArgumentError || e is UnsupportedError;

bool _bindingsEqual(List<dynamic> got, List<dynamic> expected) {
  if (got.length != expected.length) return false;
  for (var i = 0; i < got.length; i++) {
    final a = got[i], b = expected[i];
    if (a is num && b is num) {
      if (a != b) return false; // by value (int/double width not distinguished)
    } else if (a != b) {
      return false; // strict: "1" != 1, true != 1, etc.
    }
  }
  return true;
}

/// Returns null when knex-dart matches the fixture, else a description of the
/// divergence. Rethrows unexpected (non-refusal) errors so a typo in a Dart
/// case surfaces as a hard failure rather than a false "refusal".
String? _divergence(Map<String, dynamic> entry, String dialect, ParityCase b) {
  final jsRefused = entry.containsKey('error');

  SqlString? got;
  Object? refusal;
  try {
    got = b(dialect);
  } catch (e) {
    if (_isRefusal(e)) {
      refusal = e;
    } else {
      rethrow;
    }
  }
  final dartRefused = refusal != null;

  if (jsRefused && dartRefused) return null; // both refuse → parity
  if (jsRefused && !dartRefused) {
    return 'knex.js refused (${entry['error']}) but knex-dart emitted: ${got!.sql}';
  }
  if (!jsRefused && dartRefused) {
    return 'knex-dart refused ($refusal) but knex.js compiled: ${entry['sql']}';
  }

  final expectedSql = _normalizeSql(entry['sql'] as String, dialect);
  final gotSql = _normalizeSql(got!.sql, dialect);
  if (gotSql != expectedSql) {
    return 'SQL:\n  expected: $expectedSql\n  actual:   $gotSql';
  }
  final expectedBindings = (entry['bindings'] as List).cast<dynamic>();
  if (!_bindingsEqual(got.bindings, expectedBindings)) {
    return 'bindings: expected $expectedBindings, got ${got.bindings}';
  }
  return null;
}

Map<String, dynamic> _loadFixtures() {
  const rel = 'test/parity/fixtures/parity_cases.json';
  final candidates = [
    rel,
    'packages/knex_dart/$rel',
    '${Directory.current.path}/$rel',
  ];
  for (final p in candidates) {
    final f = File(p);
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  throw StateError(
    'parity_cases.json not found (looked in: ${candidates.join(", ")}). '
    'Generate it with: node tool/parity/run_js.mjs',
  );
}

void main() {
  final fixtures = _loadFixtures();
  final knexVersion = fixtures['knexVersion'];
  final entries = (fixtures['cases'] as List).cast<Map<String, dynamic>>();
  final fixtureIds = entries.map((e) => e['id'] as String).toSet();

  group('parity vs knex.js $knexVersion', () {
    // Drift guard: a Dart case with no fixture means someone forgot to
    // regenerate — it would otherwise never run.
    test('every registered case has a fixture (regenerate if this fails)', () {
      final dartOnly = parityCases.keys.toSet().difference(fixtureIds);
      expect(
        dartOnly,
        isEmpty,
        reason: 'Dart cases missing from the fixture — run '
            '`node tool/parity/run_js.mjs`: $dartOnly',
      );
    });

    for (final entry in entries) {
      final id = entry['id'] as String;
      final dialect = entry['dialect'] as String;
      final key = '$id::$dialect';

      if (_skipDialects.contains(dialect)) {
        test(key, () {}, skip: 'dialect not driven by the core harness');
        continue;
      }

      final builder = parityCases[id];
      if (builder == null) {
        test(key, () => fail('no knex-dart parity builder registered for "$id"'));
        continue;
      }

      final allowReason = parityAllowlist[key];

      test(key, () {
        final divergence = _divergence(entry, dialect, builder);
        if (allowReason == null) {
          expect(divergence, isNull, reason: divergence);
        } else {
          // Ratchet: the documented divergence MUST still be present. If it is
          // gone, the bug was fixed (or behavior drifted) — remove/re-triage.
          expect(
            divergence,
            isNotNull,
            reason: 'Allowlisted divergence is no longer present — re-triage and '
                'remove this allowlist entry:\n  $allowReason',
          );
        }
      });
    }
  });
}
