/// Differential parity harness: knex-dart vs knex.js.
///
/// Reads the committed fixture generated by `tool/parity/run_js.mjs` (knex.js
/// output, dialect-native) and, for every (case × dialect) entry, rebuilds the
/// same query with knex-dart and asserts identical SQL (after documented
/// per-dialect placeholder/quote normalization) and equal bindings.
///
/// Refusals are data: if knex.js refused a case (capability limit), knex-dart is
/// expected to refuse too. Divergences are either fixed or recorded in
/// [parityAllowlist] with a reason.
///
/// RATCHET: allowlisted entries are NOT skipped — they run in reverse. The test
/// asserts the divergence *still exists* in its known shape. So the moment a bug
/// is fixed (or an accepted behavior drifts), the allowlisted test fails and
/// forces the entry to be re-triaged / removed. A green suite therefore means
/// "every diff is fixed OR still-diverging-as-documented", never "silently ok".
///
/// Binding equality note: numbers compare by value, so int-vs-double width is
/// NOT distinguished (JSON collapses `2.0`→`2` anyway); string-vs-number IS
/// (`"1"` ≠ `1`). No case currently depends on numeric width.
///
/// Regenerate fixtures: `node tool/parity/run_js.mjs`
library;

import 'dart:convert';
import 'dart:io';

import 'package:knex_dart/knex_dart.dart';
import 'package:test/test.dart';

import 'parity_cases.dart';

/// Triage ledger of known divergences, keyed `id::dialect`. Every entry MUST
/// carry a reason. Two classes:
///   [ACCEPTED] — intentional & valid; knex-dart is right (often *more* correct
///               than knex.js, which silently drops unsupported constructs).
///   [OPEN BUG] — a real knex-dart defect the harness caught; fix then DELETE
///               the entry (the ratchet will fail the test until you do).
const Map<String, String> parityAllowlist = {
  // ── ACCEPTED: knex-dart refuses where knex.js silently drops ───────────────
  'upsert/merge::redshift':
      '[ACCEPTED] Redshift does not support ON CONFLICT. knex.js emits a plain '
          'INSERT (silently dropping the upsert!); knex-dart correctly refuses.',
  'cte/insert-multi-source::sqlite':
      '[ACCEPTED] Cosmetic multi-row INSERT syntax choice on SQLite: knex.js\'s '
          "sqlite3 client always compiles multi-row inserts as "
          '`select ? as col union all select ? as col ...` (a compatibility '
          'shim for SQLite versions predating multi-row VALUES support, '
          '<3.7.11/2012). knex-dart emits standard `values (?, ?), (?, ?)`, '
          'which every SQLite version knex-dart targets supports natively. '
          'Both are semantically identical INSERTs; same class as the '
          'documented MySQL `ADD COLUMN` vs `ADD` cosmetic-equivalence entries.',
  'cte/insert-multi-source::turso':
      '[ACCEPTED] see cte/insert-multi-source::sqlite (turso is sqlite-family, '
          'and libSQL/turso has supported multi-row VALUES since inception).',
  'cte/insert-multi-source::d1':
      '[ACCEPTED] see cte/insert-multi-source::sqlite (d1 is sqlite-family, '
          'and Cloudflare D1 (SQLite 3.4x+) supports multi-row VALUES).',
  'dml/onconflict-ignore::redshift':
      '[ACCEPTED] see upsert/merge::redshift — Redshift has no ON CONFLICT; '
          'knex.js silently emits a plain INSERT, knex-dart correctly refuses.',
  'dml/onconflict-composite-ignore::redshift':
      '[ACCEPTED] see upsert/merge::redshift (composite conflict target, same '
          'Redshift ON CONFLICT gap).',
  'dml/onconflict-merge-explicit::redshift':
      '[ACCEPTED] see upsert/merge::redshift (.merge() with explicit update '
          'values, same Redshift ON CONFLICT gap).',
  'dml/onconflict-merge-implicit-multi::redshift':
      '[ACCEPTED] see upsert/merge::redshift (.merge() with implicit '
          'excluded-column updates, same Redshift ON CONFLICT gap).',
  'dml/onconflict-raw-target::redshift':
      '[ACCEPTED] see upsert/merge::redshift (raw partial-index conflict '
          'target, same Redshift ON CONFLICT gap).',
  'dml/onconflict-merge-where::redshift':
      '[ACCEPTED] see upsert/merge::redshift (.merge().where() guard, same '
          'Redshift ON CONFLICT gap).',
  'dml/onconflict-ignore::sqlite':
      '[ACCEPTED] see cte/insert-multi-source::sqlite — multi-row INSERT '
          '...ON CONFLICT is the same union-all-select vs standard-VALUES '
          'cosmetic syntax choice.',
  'dml/onconflict-ignore::turso':
      '[ACCEPTED] see dml/onconflict-ignore::sqlite (turso is sqlite-family).',
  'dml/onconflict-ignore::d1':
      '[ACCEPTED] see dml/onconflict-ignore::sqlite (d1 is sqlite-family).',
  'dml/onconflict-merge-explicit::sqlite':
      '[ACCEPTED] see dml/onconflict-ignore::sqlite (same union-all-select vs '
          'VALUES divergence, this time with .merge() with explicit values).',
  'dml/onconflict-merge-explicit::turso':
      '[ACCEPTED] see dml/onconflict-merge-explicit::sqlite (turso is '
          'sqlite-family).',
  'dml/onconflict-merge-explicit::d1':
      '[ACCEPTED] see dml/onconflict-merge-explicit::sqlite (d1 is '
          'sqlite-family).',
  'dml/onconflict-merge-implicit-multi::sqlite':
      '[ACCEPTED] see dml/onconflict-ignore::sqlite (same union-all-select vs '
          'VALUES divergence, this time with implicit-excluded-column merge).',
  'dml/onconflict-merge-implicit-multi::turso':
      '[ACCEPTED] see dml/onconflict-merge-implicit-multi::sqlite (turso is '
          'sqlite-family).',
  'dml/onconflict-merge-implicit-multi::d1':
      '[ACCEPTED] see dml/onconflict-merge-implicit-multi::sqlite (d1 is '
          'sqlite-family).',
  'dml/onconflict-raw-target::sqlite':
      '[ACCEPTED] see dml/onconflict-ignore::sqlite (same union-all-select vs '
          'VALUES divergence, this time with a raw partial-index target).',
  'dml/onconflict-raw-target::turso':
      '[ACCEPTED] see dml/onconflict-raw-target::sqlite (turso is '
          'sqlite-family).',
  'dml/onconflict-raw-target::d1':
      '[ACCEPTED] see dml/onconflict-raw-target::sqlite (d1 is sqlite-family).',

  // ── OPEN BUG: real knex-dart defects to fix (then delete these) ────────────
  'returning/insert::sqlite':
      '[OPEN BUG] SQLite >=3.35 supports RETURNING and knex.js emits it, but '
          "knex-dart's capability matrix omits `returning` for sqlite, so it "
          'wrongly throws. Fix: add returning to the sqlite/turso/d1 caps.',
  'returning/insert::turso':
      '[OPEN BUG] see returning/insert::sqlite (turso is sqlite-family).',
  'returning/insert::d1':
      '[OPEN BUG] see returning/insert::sqlite (d1 is sqlite-family).',
  'cte/update-source::sqlite':
      '[OPEN BUG] see returning/insert::sqlite — same capability-matrix gap, '
          'this time on an UPDATE...RETURNING used as a CTE body instead of '
          'INSERT...RETURNING.',
  'cte/update-source::turso':
      '[OPEN BUG] see cte/update-source::sqlite (turso is sqlite-family).',
  'cte/update-source::d1':
      '[OPEN BUG] see cte/update-source::sqlite (d1 is sqlite-family).',
  'dml/returning-multi-insert::sqlite':
      '[OPEN BUG] see returning/insert::sqlite (multi-row insert, same '
          'capability-matrix gap).',
  'dml/returning-multi-insert::turso':
      '[OPEN BUG] see dml/returning-multi-insert::sqlite (turso is '
          'sqlite-family).',
  'dml/returning-multi-insert::d1':
      '[OPEN BUG] see dml/returning-multi-insert::sqlite (d1 is '
          'sqlite-family).',
  'dml/returning-update::sqlite':
      '[OPEN BUG] see returning/insert::sqlite — same capability-matrix gap, '
          'this time on UPDATE...RETURNING.',
  'dml/returning-update::turso':
      '[OPEN BUG] see dml/returning-update::sqlite (turso is sqlite-family).',
  'dml/returning-update::d1':
      '[OPEN BUG] see dml/returning-update::sqlite (d1 is sqlite-family).',
  // Note: DELETE...RETURNING on sqlite/turso/d1 is NOT the same capability
  // gap as INSERT/UPDATE...RETURNING above — knex.js's own sqlite3 dialect
  // doesn't emit RETURNING for DELETE either (verified against real
  // knex.js), so knex-dart dropping it there is a correct match, not a bug.

  // ── OPEN BUG (out of scope for this pass): uppercase `AS` ──────────────────
  // `select('foo as bar')`-style inline string aliasing routes through
  // formatter.dart's alias-detection → client.alias(wrapped, wrapped), which
  // emits uppercase `AS`. knex.js emits lowercase `as`. This is the same
  // known, separately-scoped client.alias() defect this mining pass was told
  // not to touch (packages/knex_dart/lib/src/client/client.dart) — confirmed
  // here to also affect the inline "col as alias" string-parsing path in
  // formatter.dart, not just explicit .as() calls. Fix: once client.alias()
  // is corrected to lowercase `as`, delete these entries (the ratchet will
  // force it).
  'select/old-style-alias::postgres':
      '[OPEN BUG] uppercase `AS` — see client.alias() note above this block.',
  'select/old-style-alias::cockroachdb':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/old-style-alias::redshift':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/old-style-alias::mysql':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/old-style-alias::sqlite':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/old-style-alias::turso':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/old-style-alias::d1':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::postgres':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::cockroachdb':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::redshift':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::mysql':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::sqlite':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::turso':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-trim-spaces::d1':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::postgres':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::cockroachdb':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::redshift':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::mysql':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::sqlite':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::turso':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-case-insensitive::d1':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::postgres':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::cockroachdb':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::redshift':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::mysql':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::sqlite':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::turso':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',
  'select/alias-dotted::d1':
      '[OPEN BUG] see select/old-style-alias::postgres (same client.alias() root cause).',

  // having/from-alias hits the same client.alias() uppercase-AS defect noted
  // above, via a "col as alias" select() string used as the HAVING column.
  'having/from-alias::postgres':
      '[OPEN BUG] knex-dart\'s Client.alias() emits uppercase "AS"; knex.js '
          'always emits lowercase "as". Known issue, scoped to '
          'client.alias() (out of bounds for this change) — see '
          'having/from-alias::postgres for the canonical explanation.',
  'having/from-alias::cockroachdb':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue (cockroachdb shares the postgres formatter).',
  'having/from-alias::redshift':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue (redshift shares the postgres formatter).',
  'having/from-alias::mysql':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue.',
  'having/from-alias::sqlite':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue.',
  'having/from-alias::turso':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue (turso is sqlite-family).',
  'having/from-alias::d1':
      '[OPEN BUG] see having/from-alias::postgres — same client.alias() '
          'uppercase-AS issue (d1 is sqlite-family).',
};

/// Dialects the core harness cannot drive via [KnexQuery.forClient].
const Set<String> _skipDialects = {
  'mssql', // not a core SQL-gen dialect — lives in the knex_dart_mssql package
};

/// knex-dart uses SQL-standard double quotes for SQLite; knex.js sqlite3 uses
/// backticks. Both are valid SQLite identifier quoting — normalize the surface
/// so the rest of the statement is still compared strictly.
const Set<String> _sqliteFamily = {'sqlite', 'turso', 'd1'};

String _normalizeSql(String sql, String dialect) =>
    _sqliteFamily.contains(dialect) ? sql.replaceAll('`', '"') : sql;

/// A legitimate capability/validation refusal (as opposed to a typo in a case,
/// which would be a [NoSuchMethodError]/[TypeError] and should fail the test).
bool _isRefusal(Object e) =>
    e is StateError || e is ArgumentError || e is UnsupportedError;

bool _bindingsEqual(List<dynamic> got, List<dynamic> expected) {
  if (got.length != expected.length) return false;
  for (var i = 0; i < got.length; i++) {
    final a = got[i], b = expected[i];
    if (a is num && b is num) {
      if (a != b) return false; // by value (int/double width not distinguished)
    } else if (a != b) {
      return false; // strict: "1" != 1, true != 1, etc.
    }
  }
  return true;
}

/// Returns null when knex-dart matches the fixture, else a description of the
/// divergence. Rethrows unexpected (non-refusal) errors so a typo in a Dart
/// case surfaces as a hard failure rather than a false "refusal".
String? _divergence(Map<String, dynamic> entry, String dialect, ParityCase b) {
  final jsRefused = entry.containsKey('error');

  SqlString? got;
  Object? refusal;
  try {
    got = b(dialect);
  } catch (e) {
    if (_isRefusal(e)) {
      refusal = e;
    } else {
      rethrow;
    }
  }
  final dartRefused = refusal != null;

  if (jsRefused && dartRefused) return null; // both refuse → parity
  if (jsRefused && !dartRefused) {
    return 'knex.js refused (${entry['error']}) but knex-dart emitted: ${got!.sql}';
  }
  if (!jsRefused && dartRefused) {
    return 'knex-dart refused ($refusal) but knex.js compiled: ${entry['sql']}';
  }

  final expectedSql = _normalizeSql(entry['sql'] as String, dialect);
  final gotSql = _normalizeSql(got!.sql, dialect);
  if (gotSql != expectedSql) {
    return 'SQL:\n  expected: $expectedSql\n  actual:   $gotSql';
  }
  final expectedBindings = (entry['bindings'] as List).cast<dynamic>();
  if (!_bindingsEqual(got.bindings, expectedBindings)) {
    return 'bindings: expected $expectedBindings, got ${got.bindings}';
  }
  return null;
}

Map<String, dynamic> _loadFixtures() {
  const rel = 'test/parity/fixtures/parity_cases.json';
  final candidates = [
    rel,
    'packages/knex_dart/$rel',
    '${Directory.current.path}/$rel',
  ];
  for (final p in candidates) {
    final f = File(p);
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  throw StateError(
    'parity_cases.json not found (looked in: ${candidates.join(", ")}). '
    'Generate it with: node tool/parity/run_js.mjs',
  );
}

void main() {
  final fixtures = _loadFixtures();
  final knexVersion = fixtures['knexVersion'];
  final entries = (fixtures['cases'] as List).cast<Map<String, dynamic>>();
  final fixtureIds = entries.map((e) => e['id'] as String).toSet();

  group('parity vs knex.js $knexVersion', () {
    // Drift guard: a Dart case with no fixture means someone forgot to
    // regenerate — it would otherwise never run.
    test('every registered case has a fixture (regenerate if this fails)', () {
      final dartOnly = parityCases.keys.toSet().difference(fixtureIds);
      expect(
        dartOnly,
        isEmpty,
        reason: 'Dart cases missing from the fixture — run '
            '`node tool/parity/run_js.mjs`: $dartOnly',
      );
    });

    for (final entry in entries) {
      final id = entry['id'] as String;
      final dialect = entry['dialect'] as String;
      final key = '$id::$dialect';

      if (_skipDialects.contains(dialect)) {
        test(key, () {}, skip: 'dialect not driven by the core harness');
        continue;
      }

      final builder = parityCases[id];
      if (builder == null) {
        test(key, () => fail('no knex-dart parity builder registered for "$id"'));
        continue;
      }

      final allowReason = parityAllowlist[key];

      test(key, () {
        final divergence = _divergence(entry, dialect, builder);
        if (allowReason == null) {
          expect(divergence, isNull, reason: divergence);
        } else {
          // Ratchet: the documented divergence MUST still be present. If it is
          // gone, the bug was fixed (or behavior drifted) — remove/re-triage.
          expect(
            divergence,
            isNotNull,
            reason: 'Allowlisted divergence is no longer present — re-triage and '
                'remove this allowlist entry:\n  $allowReason',
          );
        }
      });
    }
  });
}
