FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /workspace
COPY . .
RUN flutter pub get

WORKDIR /workspace/drivers/knex_dart_d1
CMD ["sh", "-c", "dart test && cd /workspace/drivers/knex_dart_snowflake && dart test"]
