FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /workspace
COPY . .
RUN flutter pub get

RUN apt-get update \
    && apt-get install -y --no-install-recommends libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/drivers/knex_dart_sqlite
CMD ["dart", "test"]
