FROM dart:stable

WORKDIR /workspace
COPY . .
RUN sed -i '/knex_dart_duckdb/d' pubspec.yaml && dart pub get

WORKDIR /workspace/drivers/knex_dart_d1
CMD ["sh", "-c", "dart test && cd /workspace/drivers/knex_dart_snowflake && dart test"]
