FROM dart:stable

WORKDIR /workspace
COPY . .
RUN dart pub get

RUN apt-get update \
    && apt-get install -y --no-install-recommends freetds-dev libct4 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/drivers/knex_dart_mssql
CMD ["sh", "-c", "dart test --exclude-tags=mssql && dart test --tags=mssql"]
