#!/usr/bin/env node
// Tags every parity-corpus case as executable-or-refused, per dialect —
// the roadmap for phase 2 (live driver execution testing, see
// drivers/*/test/integration/).
//
// This is NOT a new source of truth: it reads the already-committed
// fixtures (generated from real knex.js by run_js.mjs/run_js_schema.mjs)
// and just re-indexes them by dialect. A case is "executable" on a dialect
// if knex.js itself compiled it there without throwing — that's the
// correct executability signal, since a case knex.js itself refuses has no
// real SQL for a driver to run either.
//
// Regenerate whenever the corpus changes (new cases mined, cases removed):
//   node tool/parity/tag_executable_cases.mjs
//
// Output:
//   tool/parity/EXECUTABLE_CASES.json   — machine-readable, per dialect:
//     { executable: [ids...], refused: [{id, error}...] }
//   tool/parity/EXECUTABLE_CASES.md     — human-readable summary table +
//     full per-dialect executable-id lists, for checking off against
//     drivers/*/test/integration/ as phase 2 cases get written.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../..');

const queryFixture = JSON.parse(
  readFileSync(resolve(repoRoot, 'packages/knex_dart/test/parity/fixtures/parity_cases.json'), 'utf8'),
);
const schemaFixture = JSON.parse(
  readFileSync(resolve(repoRoot, 'packages/knex_dart/test/parity/fixtures/schema_parity_cases.json'), 'utf8'),
);

function tag(fixture, track) {
  // dialect -> { executable: [id...], refused: [{id, error}...] }
  const byDialect = {};
  for (const entry of fixture.cases) {
    const { id, dialect, error } = entry;
    byDialect[dialect] ??= { executable: [], refused: [] };
    if (error) {
      byDialect[dialect].refused.push({ id, error });
    } else {
      byDialect[dialect].executable.push(id);
    }
  }
  for (const d of Object.values(byDialect)) {
    d.executable.sort();
    d.refused.sort((a, b) => a.id.localeCompare(b.id));
  }
  return { track, dialects: byDialect };
}

const query = tag(queryFixture, 'query');
const schema = tag(schemaFixture, 'schema');

// ── Merge query + schema per dialect for the combined manifest ─────────────
const dialects = [...new Set([...Object.keys(query.dialects), ...Object.keys(schema.dialects)])].sort();
const manifest = {
  _comment:
    'GENERATED by tool/parity/tag_executable_cases.mjs from the committed ' +
    'parity fixtures — do not edit by hand. Regenerate after any corpus change.',
  generatedAt: new Date().toISOString().slice(0, 10),
  knexVersion: queryFixture.knexVersion,
  dialects: {},
};
for (const d of dialects) {
  const q = query.dialects[d] ?? { executable: [], refused: [] };
  const s = schema.dialects[d] ?? { executable: [], refused: [] };
  manifest.dialects[d] = {
    query: q,
    schema: s,
    totalExecutable: q.executable.length + s.executable.length,
    totalRefused: q.refused.length + s.refused.length,
  };
}

writeFileSync(
  resolve(__dirname, 'EXECUTABLE_CASES.json'),
  JSON.stringify(manifest, null, 2) + '\n',
);

// ── Human-readable summary ──────────────────────────────────────────────────
const lines = [];
lines.push('# Executable parity cases per dialect');
lines.push('');
lines.push(
  'GENERATED by `tool/parity/tag_executable_cases.mjs` from the committed ' +
  'parity fixtures. Do not edit by hand — regenerate after any corpus change.',
);
lines.push('');
lines.push(
  'This is the phase-2 (live driver execution testing) roadmap: for each ' +
  'dialect, the exact set of parity-corpus case ids that compile to real ' +
  'SQL on that dialect (knex.js itself doesn\'t refuse them) — i.e., the ' +
  'set that COULD get a live-execution test in `drivers/<dialect>/test/integration/`. ' +
  'A case not listed as executable for a dialect either doesn\'t apply there ' +
  '(refused/unsupported) or is a capability-guard assertion with nothing to execute.',
);
lines.push('');
lines.push('## Summary');
lines.push('');
lines.push('| Dialect | Executable (query) | Executable (schema) | Total executable | Refused |');
lines.push('|---|---|---|---|---|');
for (const d of dialects) {
  const m = manifest.dialects[d];
  lines.push(
    `| ${d} | ${m.query.executable.length} | ${m.schema.executable.length} | ${m.totalExecutable} | ${m.totalRefused} |`,
  );
}
lines.push('');
lines.push(
  '## Per-dialect executable case ids',
  '',
  'Full lists — use these to check off which cases already have a live-execution ' +
  'test in the corresponding driver package, and which still need one.',
  '',
);
for (const d of dialects) {
  const m = manifest.dialects[d];
  lines.push(`### ${d}`);
  lines.push('');
  lines.push(`<details><summary>${m.query.executable.length} query cases</summary>`);
  lines.push('');
  for (const id of m.query.executable) lines.push(`- [ ] \`${id}\``);
  lines.push('');
  lines.push('</details>');
  lines.push('');
  lines.push(`<details><summary>${m.schema.executable.length} schema cases</summary>`);
  lines.push('');
  for (const id of m.schema.executable) lines.push(`- [ ] \`${id}\``);
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

writeFileSync(resolve(__dirname, 'EXECUTABLE_CASES.md'), lines.join('\n') + '\n');

console.log(`Wrote tool/parity/EXECUTABLE_CASES.json and .md`);
for (const d of dialects) {
  const m = manifest.dialects[d];
  console.log(`  ${d}: ${m.totalExecutable} executable, ${m.totalRefused} refused`);
}
